#!/usr/bin/env bash
#FizzBuzz: Fizz on 3, Buzz on 5, FizzBuzz on both. Otherwise echo number.
for i in {1..100};do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ];then
		echo "FizzBuzz"
	elif [ $((i%3)) -eq 0 ];then
		echo "Fizz"
	elif [ $((i%5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$i"
	fi
done
