#!/usr/bin/env bash
#print numbers from 1-20 and an extra line on the 4th, 9th, and 17th loops using case and a while loop
i=1
while [ $i -le 20 ]
do
	echo "$i"
	
	case $i in 
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	(( i++ ))
done
